In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# =====================================================
# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
# =====================================================

print("\n--- Task 1 ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert NumPy array to DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)


# =====================================================
# Task 2: Synthetic Data Generation
# =====================================================

print("\n--- Task 2 ---")

df_sales = pd.DataFrame({
    "Date": pd.date_range(start="2023-01-01", periods=100),
    "Region": np.random.choice(["East", "West", "North", "South"], 100),
    "Product": np.random.choice(["Laptop", "Mouse", "Keyboard", "Monitor"], 100),
    "Sales": np.random.randint(100, 1001, 100).astype(float),
    "Quantity": np.random.randint(1, 11, 100).astype(float)
})

# Introduce NaN values
sales_nan = np.random.choice(df_sales.index, 5, replace=False)
qty_nan = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan, "Sales"] = np.nan
df_sales.loc[qty_nan, "Quantity"] = np.nan

print(df_sales.head())


# =====================================================
# Task 3: Indexing and Slicing
# =====================================================

print("\n--- Task 3 ---")

# 3.1
df3_1 = df_sales[["Region", "Sales"]]

# 3.2
df3_2 = df_sales[df_sales["Product"] == "Laptop"]

# 3.3
df3_3 = df_sales[
    (df_sales["Region"] == "East") &
    (df_sales["Sales"] > 500)
]

# 3.4
val3_4 = df_sales.loc[df_sales["Product"] == "Monitor", "Sales"].iloc[0]

print("\nRegion and Sales:")
print(df3_1.head())

print("\nLaptop Records:")
print(df3_2.head())

print("\nEast Region with Sales > 500:")
print(df3_3.head())

print("\nFirst Monitor Sales:")
print(val3_4)


# =====================================================
# Task 4: Handling Missing Values
# =====================================================

print("\n--- Task 4 ---")

# 4.1
missing_counts4_1 = df_sales.isna().sum()

# 4.2
df4_2_filled = df_sales.copy()
df4_2_filled["Sales"].fillna(df4_2_filled["Sales"].mean(), inplace=True)

# 4.3
df4_3_dropped = df_sales.dropna()

print("\nMissing Values:")
print(missing_counts4_1)

print("\nFilled Data:")
print(df4_2_filled.head())

print("\nDropped Missing Values:")
print(df4_3_dropped.head())


# =====================================================
# Task 5: Data Manipulation
# =====================================================

print("\n--- Task 5 ---")

# 5.1
df_sales["Total_Revenue"] = df_sales["Sales"] * df_sales["Quantity"]

# 5.2
df5_2_sorted = df_sales.sort_values(
    by=["Date", "Sales"],
    ascending=[True, False]
)

# 5.3
df5_3_grouped_region = df_sales.groupby("Region")[["Sales", "Quantity"]].sum()

# 5.4
df5_4_grouped_product = df_sales.groupby("Product")["Sales"].mean()

print("\nData with Total Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nSales & Quantity by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1 ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[87  3 98 40]
 [93 17 88 95]
 [ 3 92 22  6]]

DataFrame:
    A   B   C   D
0  87   3  98  40
1  93  17  88  95
2   3  92  22   6

--- Task 2 ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  South    Laptop  657.0       8.0
1 2023-01-02  South  Keyboard    NaN      10.0
2 2023-01-03  North   Monitor  246.0       8.0
3 2023-01-04   West   Monitor  470.0       9.0
4 2023-01-05  South   Monitor  783.0       2.0

--- Task 3 ---

Region and Sales:
  Region  Sales
0  South  657.0
1  South    NaN
2  North  246.0
3   West  470.0
4  South  783.0

Laptop Records:
         Date Region Product  Sales  Quantity
0  2023-01-01  South  Laptop  657.0       8.0
7  2023-01-08   West  Laptop  412.0       9.0
14 2023-01-15   West  Laptop  251.0      10.0
15 2023-01-16   We

/tmp/ipykernel_437/3106576216.py:102: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df4_2_filled["Sales"].fillna(df4_2_filled["Sales"].mean(), inplace=True)
